apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: Sjyhne
    provider: github
    repository: react-quickstart
  name: sjyhne-react-quickstart
spec:
  description: Imported application for Sjyhne/react-quickstart
  httpCloneURL: https://github.com/Sjyhne/react-quickstart.git
  org: Sjyhne
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: react-quickstart
  scheduler:
    kind: ""
    name: ""
  url: https://github.com/Sjyhne/react-quickstart.git
