apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: Sjyhne
    provider: github
    repository: scala-akka-http-quickstart
  name: sjyhne-scala-akka-http-quickstart
spec:
  description: Imported application for Sjyhne/scala-akka-http-quickstart
  httpCloneURL: https://github.com/Sjyhne/scala-akka-http-quickstart.git
  org: Sjyhne
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: scala-akka-http-quickstart
  scheduler:
    kind: ""
    name: ""
  url: https://github.com/Sjyhne/scala-akka-http-quickstart.git
