apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: Sjyhne
    provider: github
    repository: python-http
  name: sjyhne-python-http
spec:
  description: Imported application for Sjyhne/python-http
  httpCloneURL: https://github.com/Sjyhne/python-http.git
  org: Sjyhne
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: python-http
  scheduler:
    kind: ""
    name: ""
  url: https://github.com/Sjyhne/python-http.git
