apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: Sjyhne
    provider: github
    repository: testweb
  name: sjyhne-testweb
spec:
  description: Imported application for Sjyhne/testweb
  httpCloneURL: https://github.com/Sjyhne/testweb.git
  org: Sjyhne
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: testweb
  scheduler:
    kind: ""
    name: ""
  url: https://github.com/Sjyhne/testweb.git
